Document: seetaface-authorise
Title: Debian seetaface-authorise Manual
Author: <insert document author here>
Abstract: This manual describes what seetaface-authorise is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seetaface-authorise/seetaface-authorise.sgml.gz

Format: postscript
Files: /usr/share/doc/seetaface-authorise/seetaface-authorise.ps.gz

Format: text
Files: /usr/share/doc/seetaface-authorise/seetaface-authorise.text.gz

Format: HTML
Index: /usr/share/doc/seetaface-authorise/html/index.html
Files: /usr/share/doc/seetaface-authorise/html/*.html
